M3 base template
google-developer-training/basic-android-kotlin-compose-training-reply-app pull request #29
Opened 2023-03-14 22:15 UTC by OwenScott-GDS

2023-03-14 22:49 UTC, kkuan2011 requested changes

2023-03-14 22:49 UTC, kkuan2011 commented on app/build.gradle
> +    implementation 'androidx.activity:activity-compose:1.5.1'
nit: alphabetical order for these dependencies

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/AndroidManifest.xml
> +        tools:targetApi="31">
33

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/AndroidManifest.xml
> +        android:dataExtractionRules="@xml/data_extraction_rules"
You can remove dataExtractionRules and fullBackupContent and their related files

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/AndroidManifest.xml
> +
nit: remove blank line

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/java/com/example/reply/ui/theme/Theme.kt
> +    /* Other default colors to override
remove unused code

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/java/com/example/reply/ui/theme/Type.kt
> +    /* Other default text styles to override
same here

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/res/xml/backup_rules.xml
> +<?xml version="1.0" encoding="utf-8"?>
you can remove file

2023-03-14 22:49 UTC, kkuan2011 commented on app/src/main/res/xml/data_extraction_rules.xml
> +<?xml version="1.0" encoding="utf-8"?>
you can remove file

2023-03-16 18:20 UTC, kkuan2011 requested changes

2023-03-16 18:20 UTC, kkuan2011 commented on settings.gradle
> +pluginManagement {
needs license, you can see examples here: https://github.com/android/compose-samples/find/main

2023-03-21 23:27 UTC, kkuan2011 approved these changes

2023-03-24 20:32 UTC, johnshea approved these changes
lgtm

2023-04-06 17:32 UTC, merged